name: appsegdispomov
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter
  mockito: ^5.0.16 #test moquito importante 
  sqflite: ^2.0.0+4
  path_provider: ^2.0.2
  path: ^1.8.0
  image_picker: ^0.8.5+3
  permission_handler: ^10.2.0
  device_apps: ^2.2.0
  

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  android_intent_plus: ^5.1.0
  shared_preferences: ^2.3.2
  http: ^1.2.2
  fl_chart: ^0.69.0
  #permission_handler: ^11.3.1
  #permisos para red
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/mobile.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
